name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install django djangorestframework django-cors-headers drf-spectacular
          pip install pydantic python-dotenv requests
          pip install sentence-transformers faiss-cpu
          pip install black isort ruff pytest pytest-django

      - name: Lint with ruff
        run: |
          source .venv/bin/activate
          ruff check . || true

      - name: Check formatting with black
        run: |
          source .venv/bin/activate
          black --check . || true

      - name: Check imports with isort
        run: |
          source .venv/bin/activate
          isort --check-only . || true

      - name: Run migrations
        run: |
          source .venv/bin/activate
          python manage.py migrate --noinput

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: avallon_backend.settings
        run: |
          source .venv/bin/activate
          pytest -v

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
